/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(RestorAccount)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(RestorAccount)'}/Verification` | `/Verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/OtherInformation` | `/OtherInformation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(RestorAccount)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(RestorAccount)'}/Verification` | `/Verification`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/OtherInformation` | `/OtherInformation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/terms` | `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(RestorAccount)'}/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/ForgotPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(RestorAccount)'}/Verification${`?${string}` | `#${string}` | ''}` | `/Verification${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(signUp)'}/OtherInformation${`?${string}` | `#${string}` | ''}` | `/OtherInformation${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(signUp)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(signUp)'}/terms${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(RestorAccount)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(RestorAccount)'}/Verification` | `/Verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/OtherInformation` | `/OtherInformation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(signUp)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
